apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prod-apps
spec:
  interval: 5m0s
  path: ./fluxcd/prod/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: prod
