apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: frontend-oci
spec:
  interval: 1m0s
  url: oci://your-oci-registry-url
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: frontend
spec:
  interval: 5m0s
  chart:
    spec:
      chart: frontend
      sourceRef:
        kind: HelmRepository
        name: frontend-oci
      version: "0.1.0"
  values:
    service:
      port: 80
    ingress:
      enabled: true
      host: your-frontend.example.com
      tlsSecret: frontend-tls
