apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
spec:
  interval: 1m0s
  url: https://charts.bitnami.com/bitnami # TODO - find alternatives to Bitnami Helm charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgres
spec:
  interval: 5m0s
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: "15.2.5"
  values:
    architecture: standalone
    replicaCount: 1
    auth:
      username: sampleuser
      password: samplepass
      database: sampledb
